# -*- coding: utf-8 -*-
"""POO_Alura11_Annac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1gxtGRMKBEq_XYsSSBRadc_q_j9VSBg

# **Encapsulaemto**
"""

# @title Herança e Polimorfismo:


class Conta:
    def __init__(self, numero, titular, saldo=0.0, limite=1000.0):
        self._numero = numero
        self._titular = titular
        self._saldo = saldo
        self._limite = limite

    def deposita(self, valor):
        self._saldo += valor

    def saca(self, valor):
        if valor <= self._saldo + self._limite:
            self._saldo -= valor
            return True
        return False

    def atualiza(self, taxa):
        self._saldo += (
            self._saldo * taxa
        )  # Atualiza a conta de acordo com a taxa percentual
        return self._saldo

    @property
    def saldo(self):
        return self._saldo

    def __str__(self):
        return (
            f"Dados da Conta:\n"
            f"Número: {self._numero}\n"
            f"Titular: {self._titular}\n"
            f"Saldo: {self._saldo:.2f}\n"
            f"Limite: {self._limite:.2f}"
        )


class ContaCorrente(Conta):  # Herança
    def atualiza(self, taxa):
        return super().atualiza(taxa * 2)  # Polimorfismo

    def deposita(self, valor):
        self._saldo += valor - 0.10


class ContaPoupanca(Conta):
    def atualiza(self, taxa):
        return super().atualiza(taxa * 3)


class ContaInvestimento(Conta):
    def atualiza(self, taxa):
        self._saldo += self._saldo * taxa * 2.5
        if self._saldo > 5000:
            self._saldo += 10
        return self._saldo


class AtualizadorDeContas:
    def __init__(self, selic, saldo_total=0.0):
        self._selic = selic
        self._saldo_total = saldo_total

    @property
    def saldo_total(self):
        return self._saldo_total

    def roda(self, conta):
        if not isinstance(conta, Conta):
            raise TypeError("Objeto passado não é uma instância de Conta")

        print(f"\n[Atualizando Conta: {conta._numero}]")
        print(f"Saldo antes: {conta.saldo:.2f}")
        saldo_atualizado = conta.atualiza(self._selic)
        self._saldo_total += saldo_atualizado
        print(f"Saldo após: {conta.saldo:.2f}")


class Banco:
    def __init__(self, nome):
        self._nome = nome
        self._contas = []

    def adiciona(self, conta):
        self._contas.append(conta)

    def pegaConta(self, posicao):
        return self._contas[posicao]

    def pegaTotalDeContas(self):
        return len(self._contas)

    def __str__(self):
        return f"{self._nome} - Total de Contas: {self.pegaTotalDeContas()}"


# EXEMPLO DE USO

if __name__ == "__main__":
    conta_simples = Conta("123-1", "João", 1000)
    conta_corrente = ContaCorrente("123-2", "Ana", 1000)
    conta_poupanca = ContaPoupanca("123-3", "Carlos", 1000)
    conta_investimento = ContaInvestimento("123-4", "Paula", 6000)

    banco = Banco("Banco Python")
    banco.adiciona(conta_simples)
    banco.adiciona(conta_corrente)
    banco.adiciona(conta_poupanca)
    banco.adiciona(conta_investimento)

    print("==== Banco Inicial ====")
    print(banco)

    atualizador = AtualizadorDeContas(
        selic=0.01
    )  # Calcula o novo saldo com base na taxa selic

    for i in range(
        banco.pegaTotalDeContas()
    ):  # Passa por todas as contas uma por uma // Range(n): sequência de números de 0 até n-1
        conta = banco.pegaConta(i)
        atualizador.roda(conta)

    print(
        f"\nSaldo total de todas as contas após atualização: {atualizador.saldo_total:.2f}"
    )

    # Testando __str__
    print("\n==== Detalhes das Contas ====")
    for i in range(banco.pegaTotalDeContas()):
        print(banco.pegaConta(i))
        print("-" * 30)

# @title Classes Abstratas:
